apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-secrets
  namespace: devops4devs
  labels:
    app: postgres
    component: secrets
stringData:
  PGDATA: "/var/lib/postgresql/data/pgdata"
  POSTGRES_USER: "reviewfilmesapp"
  POSTGRES_DB: "reviewfilmesdb"
  POSTGRES_PASSWORD: "DevOpsappSecretPass2024"
