name: Deploy for App Service Azure

on: [push]

env:
  AZURE_WEBAPP_NAME: 'devopsproapp'    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './src'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'           # set this to the dot net version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main

  # docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #         context: "${{AZURE_WEBAPP_PACKAGE_PATH}}/Dockerfile"
  #         push: true
      
      # Run dotnet build and publish
      # - name: dotnet build and publish
      #   run: |
      #     dotnet restore
      #     dotnet build --configuration Release
      #     dotnet publish -c Release --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
          
      # Deploy to Azure Web apps
      # - name: 'Run Azure webapp deploy action using publish profile credentials'
      #   uses: azure/webapps-deploy@v3
      #   with: 
      #     app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
      #     package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
