name: Deploy para o App Service Azure

on: [push]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Login no Docker Hub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Construir e Enviar Imagem Docker
      uses: docker/build-push-action@v6.2.0
      with:
        context: ./src
        push: true
        file: ./src/Review-Filmes.Web/Dockerfile
        tags: |
          ${{ secrets.DOCKERHUB_REGISTRY }}/devops4devs-02:v${{ github.run_number }}
          ${{ secrets.DOCKERHUB_REGISTRY }}/devops4devs-02:latest

            
      # Run dotnet build and publish
      # - name: dotnet build and publish
      #   run: |
      #     dotnet restore
      #     dotnet build --configuration Release
      #     dotnet publish -c Release --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
          
      # Deploy to Azure Web apps
      # - name: 'Run Azure webapp deploy action using publish profile credentials'
      #   uses: azure/webapps-deploy@v3
      #   with: 
      #     app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
      #     package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
