name: Deploy for App Service Azure

on: [push]

env:
  AZURE_WEBAPP_NAME: 'devopsproapp'    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './src'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'           # set this to the dot net version to use

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main

  docker:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      -
        name: Build and Push
        run: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker build -t ${{ secrets.DOCKERHUB_REGISTRY}}/devops4devs-02: ${{ github.run_id }}
      
      # Run dotnet build and publish
      # - name: dotnet build and publish
      #   run: |
      #     dotnet restore
      #     dotnet build --configuration Release
      #     dotnet publish -c Release --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
          
      # Deploy to Azure Web apps
      # - name: 'Run Azure webapp deploy action using publish profile credentials'
      #   uses: azure/webapps-deploy@v3
      #   with: 
      #     app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
      #     package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
